name: Build Test

on:
 push:
  branches: [main, master]
 pull_request:
  branches: [main, master]

jobs:
 test-build:
  runs-on: windows-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up Go
     uses: actions/setup-go@v4
     with:
      go-version: "1.24"

   - name: Install Fyne
     run: go install fyne.io/fyne/v2/cmd/fyne@latest

   - name: Install dependencies
     run: go mod download

   - name: Verify Go build
     run: go build -v ./...

   - name: Test Fyne package build
     run: fyne package -os windows -icon icon.png

   - name: Verify executable was created
     shell: bash
     run: |
      if [ -f "modhelper.exe" ]; then
        echo "✅ Build successful: modhelper.exe created"
        ls -la modhelper.exe
      else
        echo "❌ Build failed: modhelper.exe not found"
        ls -la
        exit 1
      fi
